### ISSUE TITLE
vaadin-gradle-plugin 17.0.1 does not work with latest flow-server

### ISSUE THREAD

**Issue by stbischof** [vaadin/vaadin-gradle-plugin#100] opened 2020-12-16 19:07 UTC
**Desktop (please complete the following information):**
 - Vaadin Plugin version: flowserver-latest SNAPSHOT and vaadin-gradle-plugin 17.0.1

**Describe the bug**
vaadin-gradle-plugin 17.0.1 does not work with newest snapshot version since https://github.com/vaadin/flow/commit/bd84a1d4a7932f92c2f08f30cfe015ec59969a73

```
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.vaadin.flow.server.webcomponent.WebComponentModulesWriter$DirectoryWriter.generateWebComponentsToDirectory(WebComponentModulesWriter.java:237)
        at com.vaadin.flow.server.frontend.FrontendWebComponentGenerator.generateWebComponents(FrontendWebComponentGenerator.java:85)
        at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:510)
        at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:46)
        at com.vaadin.flow.server.frontend.NodeTasks$Builder.build(NodeTasks.java:187)

```

**Comment by mvysny** [comment] 2020-12-17 07:33
Hello, thank you for letting me know! Unfortunately I am unable to reproduce the issue on Vaadin 19.0.0.alpha1. I've pushed an example project to https://github.com/vaadin/base-starter-gradle/tree/master (the master branch) - running `./gradlew vaadinClean build appRun` works for me and will start the app correctly.

Could you please post a zip of a project which fails to build for you?

**Comment by mvysny** [comment] 2020-12-17 07:58
You're right! I've managed to reproduce the issue. Steps to reproduce:

1. check out https://github.com/vaadin/base-starter-gradle/tree/master
2. Build with `./gradlew -Pvaadin.productionMode`.

**Comment by mvysny** [comment] 2020-12-17 12:22
I've proposed a much simplified maintenance scheme to the upstream: https://github.com/vaadin/flow/issues/9685

**Comment by ollin** [comment] 2021-03-15 10:20
Hello, as far as I can see the [vaadin/flow#9685](https://github.com/vaadin/flow/issues/9685) is solved. Do you have any plans when you can integrate the extracted part so that this bug goes away?

**Comment by mvysny** [comment] 2021-03-15 10:47
In fact yes. The flow ticket is going to be eventually merged into vaadin 20.alpha or such. When it does (or a bit before perhaps), I'll work on the support from the Gradle plugin side. However, the target for this is vaadin 20.

**Comment by mvysny** [comment] 2021-03-18 05:39
A preliminary support for Vaadin 20 has been developed at https://github.com/vaadin/vaadin-gradle-plugin/tree/feature/vaadin20 . All tests pass, which is really encouraging. It is possible that the plugin will also work with Vaadin 19. I will test a bit today, then we can hopefully release. Stay tuned :)

**Comment by stbischof** [comment] 2021-03-18 06:23
This would have effect on the Plugin. 
https://github.com/vaadin/flow/pull/10319

**Comment by mvysny** [comment] 2021-03-18 06:41
@stbischof sounds good! However, to keep track, could you please open a new bug report, explaining why it would be good to have such a config option? I will then track the PR and flow releases.

**Comment by stbischof** [comment] 2021-03-18 06:43
Is this one in flow enough
Or should i open an issues here?
https://github.com/vaadin/flow/issues/10318

**Comment by mvysny** [comment] 2021-03-18 06:49
Please also open a ticket here, because the Gradle plugin then needs to expose the config setting in the Extension.

**Comment by mvysny** [comment] 2021-03-18 07:43
We will release a new version of the plugin soonish, but there will be one known issue:
* #107 - it will effectively prevent you from using LitTemplate or PolymerTemplate until we figure it out.

**Comment by mvysny** [comment] 2021-03-18 07:46
PR: #105

**Closed** 2021-03-18 12:57 UTC
Labels: bug

**Comment by mvysny** [comment] 2021-03-18 17:06
Vaadin Gradle plugin 0.20.0.0.alpha3 has been released, enjoy :+1: I'm porting the example apps now.

**Comment by evan-miller-jumpmind** [comment] 2021-05-11 15:48
I'm trying to use the unofficial version of the plugin (0.14.5.1) to build a Vaadin 14 application and I'm encountering this same issue. Would it be possible to fix it for this version as well, or are there any workarounds I can try?

**Comment by mvysny** [comment] 2021-05-12 05:40
Yes I've also encountered similar bug when building an app with plugin 0.14.5.1 and Vaadin 14.6.0. Could you open a new bug report in this regard please?
