### ISSUE TITLE
Build failed - Unable to compute frontend dependencies

### ISSUE THREAD

**Issue by mcooper7290** [vaadin/vaadin-gradle-plugin#81] opened 2020-07-29 01:35 UTC
**Desktop (please complete the following information):**
 - OS: Windows
 - JDK version: OpenJDK 8
 - Gradle version: 6.5.1
 - Vaadin Plugin version: 0.8.0 and 0.7.0

**Describe the bug**
When running "gradle vaadinBuildFrontend" it fails with "Unable to compute frontend dependencies".  This occurs if the same command has been previously run and the gradle daemon is still running.

If I kill the gradle daemon and run the same command again it works.  

Full stacktrace attached.

[gradle-stacktrace.txt](https://github.com/vaadin/vaadin-gradle-plugin/files/4991974/gradle-stacktrace.txt)

**To Reproduce**
1. Setup project  '...'
2. Run Gradle task '....''
4. See error '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mvysny** [comment] 2020-08-26 16:42
Hi, thank you for letting us know. Could you please try running Gradle again, but this time with `--stacktrace --info` switches? That should provide much more insight as to what's going on.

**Comment by mcooper7290** [comment] 2020-09-10 01:35
The log.0.txt file contains output from "gradle --stacktrace --info vaadinBuildFrontend" with the failure.  After that I ran "gradle --stop" and then the same "gradle --stacktrace --info vaadinBuildFrontend" which succeeds (see log.1.after.stop.t.xt).

[log.0.txt](https://github.com/vaadin/vaadin-gradle-plugin/files/5198650/log.0.txt)
[log.1.after.stop.txt](https://github.com/vaadin/vaadin-gradle-plugin/files/5198652/log.1.after.stop.txt)

**Comment by mvysny** [comment] 2020-09-10 05:35
This looks to be the source of the exception:
```
JAR entry cmb/cabridge/api/entity/SubjectBindingEntity.class not found in C:\Users\mcooper\ws\cmb\6.0\CmbProduct\Common\build\libs\Common-6.0.85.jar
```

It could be a bug in Vaadin's class discovery code. Could you please verify that the class exists in the jar file?

**Comment by mcooper7290** [comment] 2020-09-10 18:18
Yes the SubjectBindingEntity.class file is definitely in the Common-X.X.X.jar file.

I ran again using "--no-parallel" and got a similar failure, though it reported a different file:

`Caused by: java.io.FileNotFoundException: JAR entry cmb/model/entity/CertificatePurposeEntity.class not found in C:\Users\mcooper\ws\cmb\6.0\CmbProduct\Model\build\libs\Model-6.0.86.jar`

I also confirmed Model-6.0.86.jar contains CertificatePurposeEntity.class

[log.2.no-parallel.txt](https://github.com/vaadin/vaadin-gradle-plugin/files/5203884/log.2.no-parallel.txt)

**Comment by mvysny** [comment] 2020-09-11 06:45
Thank you so much!

This bug is really curious. Comparing the two stack traces:

```
Caused by: java.io.FileNotFoundException: JAR entry cmb/model/entity/CertificatePurposeEntity.class not found in C:\Users\mcooper\ws\cmb\6.0\CmbProduct\Model\build\libs\Model-6.0.86.jar
	at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:467)
	at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:479)
```

and the older one

```
Caused by: java.io.FileNotFoundException: JAR entry cmb/cabridge/api/entity/SubjectBindingEntity.class not found in C:\Users\mcooper\ws\cmb\6.0\CmbProduct\Common\build\libs\Common-6.0.85.jar
	at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:467)
	at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:479)
```

we can see that the bug is "caused" by different jar files. That hints to some kind of a threading issue, or alternatively all the files are "somehow broken" at that very point in time, and it's just the matter of iteration order.

I've tried to investigate the stacktrace, but to no avail: the exception is apparently thrown directly by the call to `url.openStream()` - that's not possible since the exception can only be thrown by a `throws` clause. This suggests that the JVM is "lying" to us, or somehow collapses the stack-traces. I've found that such an exception can only be thrown at two places on my OpenJDK 1.8: the `sun.net.www.protocol.jar.JarURLConnection:142` and `sun.net.www.protocol.jar.JarURLConnection:160`. The code is pretty horrible and quickly jumps into native code, so it's really hard to see what's going on and whether there actually is a cause exception, masked by the code somewhere.

However, upon investigating, I've discovered that Flow doesn't close the InputStream properly when reading the Class file. Could this be the cause we are looking for? My current theory is that since Flow doesn't close the files properly, they stay open and locked until the Gradle Daemon is running. Running another Gradle build may run another daemon process, which will try to open the same jar files and fail to do so, since they're opened by the other Daemon process. Instead of reporting this fact cleanly, the JVM code swallows the exception and throws FileNotFoundException instead.

This theory is supported by the fact that everything start to work once you kill the Gradle Daemon process. However, opening a file for reading usually doesn't create an exclusive lock on the file, therefore other processes should be able to open the very same jar file for reading as well, which somewhat disproves the hypothesis... Perhaps `JarFile` accidentally uses exclusive locks?

Could you please try killing the gradle daemon, then building the project repeatedly with `--no-daemon` flag? If the build succeeds, that would hint that the theory is indeed valid.

Nevertheless, I've created a pull request for Vaadin Flow to correctly close those InputStreams, which could hopefully fix this issue as well :+1:  https://github.com/vaadin/flow/pull/9002

**Comment by mvysny** [comment] 2020-09-11 13:13
The fix has been merged into Flow and should therefore appear in the next releases of Flow: 4.0.2 for Gradle Plugin master, and 2.3.6 for Gradle Plugin 14.x.

**Comment by mcooper7290** [comment] 2020-09-11 18:41
When I used --no-daemon (e.g. "gr --no-daemon  --stacktrace --info vaadinBuildFrontend") the builds worked each time I ran them.  So this does seem to confirm your theory.

I will wait for the next releases.

Thanks for fixing!

**Comment by mvysny** [comment] 2020-09-15 05:27
Awesome, thank you for confirming :+1:  We just need to wait for the next Flow release: https://github.com/vaadin/flow/tags

**Comment by mvysny** [comment] 2020-09-24 06:02
The bug is fixed on master, however we're waiting for flow 2.3.6 release to also fix this on the 14.x branch.

**Closed** 2020-09-25 11:23 UTC
Labels: blocked by upstream, bug
