### ISSUE TITLE
Possible bug with gradle plugin "0.17.0.1" when trying -Pvaadin.productionMode with Vaadin 19

### ISSUE THREAD

**Issue by marcelbaumann** [vaadin/vaadin-gradle-plugin#108] opened 2021-03-23 10:06 UTC
**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - JDK version: java version "15.0.2" 2021-01-19
 - Gradle version: Gradle 6.8.3
 - Vaadin Plugin version: 0.17.0.1
 - Vaadin 19.0.2

**Describe the bug**
When creating Vaadin application with gradle -build everything works and the application runs.
When creating Vaadin for production gradle build -Pvaadin.productionMode got plugin error

> Task :net.tangly.ui:vaadinBuildFrontend FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':net.tangly.ui:vaadinBuildFrontend'.
> wrong number of arguments

**Additional context**
Same error with Vaadin 19.0.1 and Vaadin 19.0.0

**Comment by mvysny** [comment] 2021-03-23 11:00
The "wrong number of arguments" looks like a duplicate of #100 . Could you please try Vaadin Gradle plugin 0.20.0.0.alpha3 ? It should be also compatible with Vaadin 19.

**Comment by mvysny** [comment] 2021-03-25 15:12
Closing as duplicate of #100

**Closed by mvysny** 2021-03-25 15:12 UTC
Labels: bug, question
