### ISSUE TITLE
Calling Project.afterEvaluate on an evaluated project has been deprecated.

### ISSUE THREAD

**Issue by longkerdandy** [vaadin/vaadin-gradle-plugin#80] opened 2020-07-10 03:37 UTC
**Desktop (please complete the following information):**
 - OS: Windows 10
 - JDK version: 11
 - Gradle version: 6.5.1
 - Vaadin Plugin version: 0.7.0

**Describe the bug**
With Gradle 6.5.1 I got a warning everytime build the project. After investigation it related to [Project.afterEvaluate on an evaluated project has been deprecated.](https://docs.gradle.org/6.5.1/userguide/upgrading_version_5.html#calling_project_afterevaluate_on_an_evaluated_project_has_been_deprecated) 

Once a project is evaluated, Gradle ignores all configuration passed to Project#afterEvaluate and emits a deprecation warning. This scenario will become an error in Gradle 7.0.

**Comment by mvysny** [comment] 2020-07-10 11:03
Hi, I am unable to reproduce the message on my example project: https://github.com/mvysny/karibu10-helloworld-application . It uses a newer version of the Plugin: 0.8.0. Could you please try out the karibu10-helloworld-application whether the warning is printed as well?

**Comment by longkerdandy** [comment] 2020-07-12 06:42
Hi, I have created a demo project to reproduct the warn: https://github.com/longkerdandy/vaadin-gradle-test
It happens when add vaadin plugin to the sub-module (maybe I used it wrong)

**Comment by mvysny** [comment] 2020-07-12 17:15
Hi, for a multi-module project the recommended way is to declare the plugin in the root module but not apply it in the root project: please see https://github.com/vaadin/vaadin-gradle-plugin#multi-project-builds for more details.

That being said, I'm not a Gradle expert: in case the documentation feels odd, or if the gradle plugins should generally be able to be applied in subprojects as you suggest, just let me know and I'll take a look at the issue.

**Comment by mvysny** [comment] 2020-08-26 16:46
@longkerdandy since you mentioned that the warning actually comes from the Gretty plugin, that leads me to believe that the problem is not present in the Vaadin Gradle Plugin itself. Therefore I'm closing this bug report as invalid; please feel free to reopen if need be.

Could you also please consider opening a bug report at https://github.com/gretty-gradle-plugin/gretty regarding this issue?

**Closed by mvysny** 2020-08-26 16:46 UTC
Labels: bug
