### ISSUE TITLE
CSS of vcf-handsontable-flow does not seem to get bundled in prod mode

### ISSUE THREAD

**Issue by birgitbakshi** [vaadin/vaadin-gradle-plugin#55] opened 2020-03-24 14:34 UTC
**Desktop:**
 - Gradle version: 5.6
 - Vaadin Plugin version: 0.5.1

**Describe the bug**
We tried to use the vcf-handsontable-flow component and added it to our build.gradle.
Unfortunately the CSS files imported in the Handsontable.java using the @StyleSheet annotation do not seem to be part of the built application. For example we could not find any css instructions for the css class "handsontable" in the build artefacts using full text search. When running the application the css class is also not found by the browser, resulting in a really sad looking table.

The component works, the javascript is packaged as expected. Only the CSS is not applied correctly. Our current workaround is to add the css file to our default layout java class.

Is this a bug or do we need to change the configuration of the plugin?

The gradle task we are using to build the project:
`clean vaadinBuildFrontend build`

build.gradle :
```
dependencies {
    implementation "com.vaadin:vaadin-spring-boot-starter"
    implementation "com.vaadin:vaadin-grid-pro-flow"
    implementation "com.vaadin:vaadin-confirm-dialog-flow"
    implementation "com.vaadin:vaadin-rich-text-editor-flow"
    implementation "org.vaadin:vcf-handsontable-flow:3.0.0"
}

dependencyManagement {
    imports {
        mavenBom SpringBootPlugin.BOM_COORDINATES
        mavenBom "com.vaadin:vaadin-bom:14.1.16"
    }
}
```
Handsontable.java :
```
@JavaScript("./handsontable/dist/handsontable.full.min.js")
@StyleSheet("./handsontable/dist/handsontable.full.min.css")
@JavaScript("./handsontable/dist/languages/all.min.js")
@JavaScript("./handsontable/dist/numbro/languages.min.js")
@JavaScript("./handsontable/handsontableConnector.js")
@StyleSheet("./handsontable-extra.css")
public class Handsontable extends Div {
```
Our default layout java class with the current workaround:
```
@UIScope
@SpringComponent
@Theme(value = Lumo.class)
@StyleSheet("./handsontable/dist/handsontable.full.min.css")
@StyleSheet("./handsontable-extra.css")
public class MyMainLayout extends AppLayout {
```

**Expected behavior**
The prod application when run after build frontend should contain the CSS styles from the vcf-handsontable-flow component.

**Comment by mvysny** [comment] 2020-04-01 18:11
Thank you for letting me know! I've tried to reproduce the issue on a very simple project and everything seems to be working just fine for me. I'm attaching the (non-Spring) project here. I'm using the newer Vaadin Gradle Plugin 0.6.0 which might have couple of things fixed. Could you please try out and let me know whether it works for you? To run the project:

1. Unpack the zip file
2. Build via `./gradlew -Pvaadin.productionMode`
3. Go into `build/libs/`
4. Download the Jetty Runner and run the WAR file using the newest Jetty Runner.

[karibu10-helloworld-application.zip](https://github.com/vaadin/vaadin-gradle-plugin/files/4416883/karibu10-helloworld-application.zip)

I'm going to try out the same thing with the Spring example project, just a second.

**Comment by mvysny** [comment] 2020-04-01 18:24
The Handsontable works correctly for me in the Spring example project as well, please find it attached. To run the project:

1. Unpack the zip file
2. Build via `./gradlew -Pvaadin.productionMode`
3. Go into `build/libs/`
4. Run `java -jar *.jar`

The CSS are correctly downloaded from http://localhost:8080/frontend/handsontable/dist/handsontable.full.min.css .

Please make sure to use the `-Pvaadin.productionMode` switch; the Vaadin Gradle Plugin 0.6.0 now automatically calls the `vaadinBuildFrontend` task. The 0.6.0 version contains a couple of fixes, therefore please try to upgrade the plugin to 0.6.0 in your project.

**Comment by TatuLund** [comment] 2020-10-06 18:17
Just commenting as I have been working on that add-on. The CSS part is loaded via context:// to overcome some other issues, hence it is loaded on the fly and not even meant to be included in the bundle.

**Comment by mvysny** [comment] 2020-10-19 10:15
I'm closing the issue since we can't reproduce the issue. Please reopen if need be.

**Closed by mvysny** 2020-10-19 10:15 UTC
Labels: question
